name: Build Page

on:
  push:
    branches:
      - main
    paths:
      - frontend/**

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: To Frontend Directory
        run: cd ./frontend

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          npm install

      - name: Build Page
        run: |
          git pull
          npm run build
          git pull

      - name: Deploy
        uses: npm run start

      - name: Update GitHub
        run: |
          git config --local user.email "ethany.zhao@mail.utoronto.ca"
          git config --local user.name "Ethan-ZYF-Bot"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}
          git add *
          git commit -m "ci: build page"
          git push